### ISSUE TITLE
As soon as the image is generated by DALL-E and presented, all players (excluding the one who provided the input) are shown the image clearly on their screens.

### ISSUE THREAD

**Issue by Ericode99** [sopra-fs24-group-32/sopra-fs24-group-32-client#34]

**Comment by nicolasHuber3** [comment]
Commits on server:
[f0bd26c69f85456e588c8326225fa47acb282ef7](https://github.com/sopra-fs24-group-32/sopra-fs24-group-32-server/commit/f0bd26c69f85456e588c8326225fa47acb282ef7)

https://github.com/sopra-fs24-group-32/sopra-fs24-group-32-server/commit/ca5ac2bd8f6ba241256767e2017e801589db8c0a

https://github.com/sopra-fs24-group-32/sopra-fs24-group-32-server/commit/5c8d35ef2ea5fab24d00db87c1c385110bae644d

**Comment by eduard54** [comment]
commit: ae5423e
